// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABky8Y3IW77Dv-2Ax_bGtxF0clE5IPw4U',
    appId: '1:962590288743:web:a6dd5a2317b437067a1dc2',
    messagingSenderId: '962590288743',
    projectId: 'our-community-eda3c',
    authDomain: 'our-community-eda3c.firebaseapp.com',
    storageBucket: 'our-community-eda3c.appspot.com',
    measurementId: 'G-3FERC4YCQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj8I0Q3eR69Ng4H5mMOspU1UiJFwtc6g',
    appId: '1:962590288743:android:253b0d63e6ec2afd7a1dc2',
    messagingSenderId: '962590288743',
    projectId: 'our-community-eda3c',
    storageBucket: 'our-community-eda3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuVrUp2ZqzqUQUpc8jby2j0X01CQfyDI',
    appId: '1:962590288743:ios:ca148489750f0e307a1dc2',
    messagingSenderId: '962590288743',
    projectId: 'our-community-eda3c',
    storageBucket: 'our-community-eda3c.appspot.com',
    iosClientId:
        '962590288743-5538evk4lf0qcs213jeid4ivd7gi6knh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuVrUp2ZqzqUQUpc8jby2j0X01CQfyDI',
    appId: '1:962590288743:ios:ca148489750f0e307a1dc2',
    messagingSenderId: '962590288743',
    projectId: 'our-community-eda3c',
    storageBucket: 'our-community-eda3c.appspot.com',
    iosClientId:
        '962590288743-5538evk4lf0qcs213jeid4ivd7gi6knh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourCommunity',
  );
}
